ingress:
  name: smoke-ingress
  namespace: aks-train-smoke
  annotations:
   ingressClass: nginx
   enableCors: "true"
   rewriteTarget: /$1
  hosts:
  #NO TLS is enabled; hence traffic reaches Ingress over Http (80)
  #Private DNS Zone name
  - name: aks-train-smoke.<dns-name>
    paths:  
    - path: /healthz/?(.*)
      pathType: Prefix
      service: nginx-svc
      port: 80    