ingress:
  name: smoke-ingress
  namespace: aks-train-smoke
  annotations:
   ingressClass: nginx
   enableCors: "true"
   rewriteTarget: /$1
  tls:
  - hosts:
    - "aks-train-smoke.<dns-name>"
    secretName: aks-workshop-tls-secret
  hosts:
  - name: aks-train-smoke.<dns-name>
    paths:
    - path: /healthz/?(.*)
      pathType: Prefix
      service: nginx-svc
      port: 80
  