ingress:
  name: aks-workshop-ingress
  namespace: aks-workshop-qa
  annotations:
    ingressClass: nginx
    proxyBodySize: "10m"
    enableCors: "true"
    rewriteTarget: /$1
  tls:
  - hosts:
    - "*.<dns-name>"
    secretName: aks-workshop-tls-secret
  hosts:
  - name: qa-prv.<dns-name>
    paths:
    - path: /?(.*)
      pathType: prefix
      service: ratingsweb-service
      port: 80 
  