ingress:
  name: aks-workshop-ingress
  namespace: aks-workshop-dev
  annotations:
    ingressClass: nginx
    proxyBodySize: "10m"
    enableCors: "true"
    rewriteTarget: /$1
  tls:
  - hosts:
    - "*.<dns-name>"
    secretName: aks-workshop-tls-secret
  hosts:
  - name: dev-prv.<dns-name>
    paths:
    - path: /?(.*)
      service: ratingsweb-service
      port: 80 
  