ingress:
  name: aks-workshop-ssltest-ingress
  namespace: aks-train-ssltest
  annotations:
    ingressClass: nginx
    proxyBodySize: "10m"
    enableCors: "true"
    sslpassThrough: "true"
  hosts:
  - name: apiproxy.<dns-name>
    paths:
    - path: /
      pathType: Exact
      service: api-proxy-svc      
      port: 443
    - path: /api/post
      pathType: Exact
      service: api-proxy-svc      
      port: 443
    - path: /bkend
      pathType: Exact
      service: api-proxy-svc
      port: 443
    - path: /api/post/bkend
      pathType: Exact
      service: api-proxy-svc
      port: 443
  - name: apibkend.<dns-name>
    paths:
    - path: /
      pathType: Exact
      service: api-bkend-svc      
      port: 443
    - path: /api/post
      pathType: Exact
      service: api-bkend-svc
      port: 443    