ingress:
  name: aks-workshop-ingress
  namespace: aks-train-qa
  annotations:
    ingressClass: nginx
    proxyBodySize: "10m"
    enableCors: "true"
    rewriteTarget: /$1
  hosts:
  #NO TLS is enabled; hence traffic reaches Ingress over Http (80)
  #Private DNS Zone name
  - name: aks-train-qa.<dns-name>
    paths:
    - path: /?(.*)
      pathType: Prefix
      service: ratingsweb-service
      port: 80