ingress:
  name: aks-workshop-ingress
  namespace: aks-train-qa
  annotations:
    ingressClass: nginx
    proxyBodySize: "10m"
    enableCors: "true"
    rewriteTarget: /$1
  tls:
  #TLS is enabled; hence traffic reaches Ingress over Https (443)
  #TLS is offloaded at Ingress
  - hosts:
    #K8s secret for holding the TLS Certificate
    - "*.<dns-name>"
    secretName: aks-workshop-tls-secret
  hosts:
  #Private DNS Zone name
  - name: aks-train-qa.<dns-name>
    paths:
    - path: /?(.*)
      pathType: Prefix
      service: ratingsweb-service
      port: 80 
  