netpols:
  name: ratingsapi-netpol
  namespace: aks-train-dev
  podLabels:
    app: ratingsapi-pod
  policyTypes:
  - Ingress
  ingresses:
  - sources:
    - podSelector:
        matchLabels:
          app: ratingsweb-pod
    - namespaceSelector:
        matchLabels:
          name: aks-train-ing-ns
    ports:
    - protocol: TCP
      port: 3000
    