netpols:
  name: ratingsapi-netpol
  namespace: aks-workshop-dev
  podLabels:
    app: ratingsapi-pod
  policyTypes:
  - Ingress
  ingresses:
  - podLabels:
      app: ratingsweb-pod 
    ports:
    - protocol: TCP
      port: 3000
  - namespaceLabels:
      name: aks-workshop-cluster-ing-ns    
    ports:
    - protocol: TCP
      port: 3000