netpols:  
  name: ratingsweb-netpol
  namespace: aks-train-dev
  podLabels:
    app: ratingsweb-pod
  policyTypes:
  - Ingress
  - Egress
  ingresses:
  - sources:
    - namespaceSelector:
        matchLabels:
          name: aks-train-ing-ns          
    ports:
    - protocol: TCP
      port: 8080
  egresses:
  #Allow all Egress
  - {}

  #Enable this to make Egress restrictions
  # - destinations:
  #   - podSelector:
  #       matchLabels:
  #         app: ratingsapi-pod

  #Enable/Diasble this to see changes in Egress flow
  #kubectl label namespace kube-system name=kube-system
    # - namespaceSelector:
    #     matchLabels:
    #       name: kube-system
    #   podSelector:
    #     matchLabels:
    #       k8s-app: kube-dns

  #Enable this to make Egress restrictions
    # ports:
    # - protocol: TCP
    #   port: 3000

  #Enable/Diasble this to see changes in Egress flow
    # - protocol: TCP
    #   port: 53
    # - protocol: UDP
    #   port: 53